name: utils_pagination
description: "This package provides pagination utilities."
publish_to: "none"
version: 0.0.1

environment:
  sdk: ^3.6.0
  flutter: ^3.27.1

resolution: workspace

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  freezed_annotation: ^2.4.4
  visibility_detector: ^0.4.0+2

dev_dependencies:
  build_runner: ^2.4.14
  custom_lint: ^0.7.0
  freezed: ^2.5.7
  riverpod_lint: ^2.6.3
