name: cores_core
description: "This package provides core features of app."
publish_to: 'none'
version: 0.0.1

environment:
  sdk: ^3.3.1
  flutter: ^3.19.3

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  riverpod_annotation: ^2.3.5
  simple_logger: ^1.9.0+3

dev_dependencies:
  build_runner: ^2.4.7
  custom_lint: ^0.6.4
  flutter_test:
    sdk: flutter
  freezed: ^2.4.7
  json_serializable: ^6.7.1
  riverpod_generator: ^2.4.0
  riverpod_lint: ^2.3.10
  yumemi_lints: ^1.3.0
