name: cores_core
description: "This package provides core features of app."
publish_to: 'none'
version: 0.0.1

environment:
  sdk: ^3.2.3
  flutter: ^3.16.4

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.4.9
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  package_info_plus: ^5.0.1
  riverpod_annotation: ^2.3.3
  simple_logger: ^1.9.0+3

dev_dependencies:
  build_runner: ^2.4.7
  custom_lint: ^0.5.8
  flutter_test:
    sdk: flutter
  freezed: ^2.4.6
  json_serializable: ^6.7.1
  riverpod_generator: ^2.3.9
  riverpod_lint: ^2.3.7
  yumemi_lints: ^1.3.0
