name: cores_navigation
description: "A new Flutter package project."
version: 0.0.1

environment:
  sdk: ">=3.2.3 <4.0.0"
  flutter: ^3.16.4

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.4.9
  riverpod_annotation: ^2.3.3

dev_dependencies:
  build_runner: ^2.4.7
  custom_lint: ^0.5.11
  flutter_test:
    sdk: flutter
  riverpod_generator: ^2.3.9
  riverpod_lint: ^2.3.7
  yumemi_lints: ^1.3.0

flutter:
