name: features_webview
description: "This package provides webview feature."
publish_to: "none"
version: 0.0.1

environment:
  sdk: ^3.6.0
  flutter: ^3.27.1

dependencies:
  flutter:
    sdk: flutter
  flutter_hooks: ^0.20.5
  flutter_inappwebview: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  yumemi_lints: ^2.2.0

flutter:
  uses-material-design: true
