name: samples_github_repository
description: "This package provides sample GitHub repository functionality."
publish_to: 'none'
version: 0.0.1

environment:
  sdk: ^3.6.0
  flutter: ^3.27.1

resolution: workspace

dependencies:
  cores_core:
    path: ../../cores/core
  cores_data:
    path: ../../cores/data
  cores_designsystem:
    path: ../../cores/designsystem
  flutter:
    sdk: flutter
  flutter_hooks: ^0.20.5
  freezed_annotation: ^2.4.4
  hooks_riverpod: ^2.6.1
  json_annotation: ^4.9.0
  riverpod_annotation: ^2.6.1
  utils_pagination:
    path: ../../utils/pagination

dev_dependencies:
  build_runner: ^2.4.14
  custom_lint: ^0.7.0
  freezed: ^2.5.7
  json_serializable: ^6.9.0
  riverpod_generator: ^2.6.3
  riverpod_lint: ^2.6.3
