name: cores_init
description: "This package provides ways to initialize app."
publish_to: 'none'
version: 0.0.1

environment:
  sdk: ^3.2.3
  flutter: ^3.16.4

dependencies:
  cores_data:
    path: ../data
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.4.9
  shared_preferences: ^2.2.2

dev_dependencies:
  custom_lint: ^0.5.8
  riverpod_lint: ^2.3.7
  yumemi_lints: ^1.3.0
