name: cores_init
description: "This package provides ways to initialize app."
publish_to: 'none'
version: 0.0.1

environment:
  sdk: ^3.3.1
  flutter: ^3.19.3

dependencies:
  cores_core:
    path: ../core
  cores_data:
    path: ../data
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  shared_preferences: ^2.2.2

dev_dependencies:
  custom_lint: ^0.6.4
  riverpod_lint: ^2.3.10
  yumemi_lints: ^1.3.0
