name: cores_model
description: This package provides model classes.
version: 0.1.0
publish_to: "none"

environment:
  sdk: ^3.6.0

resolution: workspace

dependencies:
  freezed_annotation: ^2.4.4

dev_dependencies:
  build_runner: ^2.4.14
  freezed: ^2.5.7
  test: ^1.25.8
