name: internal_design_theme
description: アプリ全体で利用されるカラーパレットやタイポグラフィなど、デザインテーマを定義するパッケージです。
publish_to: "none"
version: 1.0.0

environment:
  sdk: ^3.8.0
  flutter: ^3.32.0

resolution: workspace

dependencies:
  flutter:
    sdk: flutter
  theme_extensions_builder_annotation: ^3.1.0

dev_dependencies:
  build_runner: ^2.4.15
  flutter_test:
    sdk: flutter
  theme_extensions_builder: ^3.1.0

flutter:
  uses-material-design: true
