name: internal_application
description: アプリケーション層のロジックを提供し、ユースケースやサービスの調整を担うパッケージです。
publish_to: "none"
version: 1.0.0

environment:
  sdk: ^3.8.0

resolution: workspace

dependencies:
  internal_domain_logic:
    path: ../domain_logic
  internal_domain_model:
    path: ../domain_model

dev_dependencies:
  test: ^1.25.8
