name: features_force_update
description: "This package provides forced update feature."
publish_to: 'none'
version: 0.0.1

environment:
  sdk: ^3.6.0
  flutter: ^3.27.1

resolution: workspace

dependencies:
  cores_core:
    path: ../../cores/core
  cores_model:
    path: ../../cores/model
  cores_ui:
    path: ../../cores/ui
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  freezed_annotation: ^2.4.4
  riverpod_annotation: ^2.6.1

dev_dependencies:
  build_runner: ^2.4.14
  custom_lint: ^0.7.0
  flutter_test:
    sdk: flutter
  freezed: ^2.5.7
  riverpod_generator: ^2.6.3
  riverpod_lint: ^2.6.3

flutter:
  uses-material-design: true
