name: catalog
description: "A UI catalog application."
publish_to: "none"
version: 0.0.1

environment:
  sdk: ^3.6.0
  flutter: ^3.27.1

resolution: workspace

dependencies:
  alchemist: ^0.11.0
  cores_designsystem:
    path: ../../packages/cores/designsystem
  cores_model:
    path: ../../packages/cores/model
  cores_ui:
    path: ../../packages/cores/ui
  flutter:
    sdk: flutter
  flutter_test:
    sdk: flutter
  widgetbook: ^3.10.1
  widgetbook_annotation: ^3.2.0

dev_dependencies:
  build_runner: ^2.4.14
  widgetbook_generator: ^3.9.1

flutter:
  uses-material-design: true
