name: features_setting
description: "This package provides setting feature."
publish_to: 'none'
version: 0.0.1

environment:
  sdk: ^3.3.1
  flutter: ^3.19.3

dependencies:
  cores_core:
    path: ../../../packages/cores/core
  cores_data:
    path: ../../../packages/cores/data
  cores_navigation:
    path: ../../../packages/cores/navigation
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  intl: ^0.18.1

dev_dependencies:
  yumemi_lints: ^1.3.0

flutter:
  uses-material-design: true
