name: features_setting
description: "This package provides setting feature."
publish_to: "none"
version: 0.0.1

environment:
  sdk: ^3.4.1
  flutter: ^3.22.1

dependencies:
  cores_core:
    path: ../../cores/core
  cores_data:
    path: ../../cores/data
  cores_navigation:
    path: ../../cores/navigation
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  intl: ^0.19.0

dev_dependencies:
  build_runner: ^2.4.7
  flutter_gen_runner: ^5.5.0+1
  yumemi_lints: ^2.1.0

flutter:
  uses-material-design: true

  assets:
    - assets/

flutter_gen:
  assets:
    outputs:
      package_parameter_enabled: true
