name: features_debug_mode
description: "This package provides features for Debug Mode"
publish_to: "none"
version: 0.0.1

environment:
  sdk: ^3.6.0
  flutter: ^3.27.1

resolution: workspace

dependencies:
  cores_core:
    path: ../../cores/core
  cores_data:
    path: ../../cores/data
  cores_designsystem:
    path: ../../cores/designsystem
  cores_model:
    path: ../../cores/model
  cores_ui:
    path: ../../cores/ui
  dio: ^5.7.0
  features_force_update:
    path: ../force_update
  features_maintain:
    path: ../maintain
  flutter:
    sdk: flutter
  flutter_hooks: ^0.20.5
  flutter_riverpod: ^2.6.1
  go_router: ^14.6.3
  path: ^1.9.0
  riverpod_annotation: ^2.6.1

dev_dependencies:
  build_runner: ^2.4.14
  custom_lint: ^0.7.0
  riverpod_generator: ^2.6.3
  riverpod_lint: ^2.6.3
