name: github_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.4.1
  flutter: ^3.22.1

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  yumemi_lints: ^2.1.0

flutter:
  uses-material-design: true
