name: website
description: "document viewer"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.4.1
  flutter: ^3.22.1

dependencies:
  flutter:
    sdk: flutter
  flutter_hooks: ^0.20.5
  flutter_markdown: ^0.7.3
  go_router: ^14.6.2

dev_dependencies:
  build_runner: ^2.4.11
  go_router_builder: ^2.7.1
  yumemi_lints: ^2.2.0

flutter:
  uses-material-design: true
  assets:
    - assets/docs/ja/
    - assets/docs/en/
    - assets/docs/images/
