name: website
description: "document viewer"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.0
  flutter: ^3.27.1

dependencies:
  flutter:
    sdk: flutter
  flutter_hooks: ^0.20.5
  flutter_markdown: ^0.7.5
  go_router: ^14.6.3

dev_dependencies:
  build_runner: ^2.4.14
  go_router_builder: ^2.7.2
  yumemi_lints: ^2.2.0

flutter:
  uses-material-design: true
  assets:
    - assets/docs/ja/
    - assets/docs/en/
    - assets/docs/images/
