name: flutter_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.0.1

environment:
  sdk: ^3.3.1
  flutter: ^3.19.3

dependencies:
  cores_core:
    path: ../../packages/cores/core
  cores_data:
    path: ../../packages/cores/data
  cores_designsystem:
    path: ../../packages/cores/designsystem
  cores_init:
    path: ../../packages/cores/init
  cores_navigation:
    path: ../../packages/cores/navigation
  features_debug_mode:
    path: ../../packages/features/debug_mode
  features_github_repository:
    path: ../../packages/features/github_repository
  features_setting:
    path: ../../packages/features/setting
  features_webview:
    path: ../../packages/features/webview
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  freezed_annotation: ^2.4.1
  go_router: ^13.0.1
  intl: ^0.18.1
  json_annotation: ^4.8.1
  package_info_plus: ^5.0.1
  riverpod_annotation: ^2.3.5

dev_dependencies:
  build_runner: ^2.4.7
  build_verify: ^3.1.0
  custom_lint: ^0.6.4
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter
  freezed: ^2.4.7
  go_router_builder: ^2.4.1
  json_serializable: ^6.7.1
  riverpod_generator: ^2.4.0
  riverpod_lint: ^2.3.10
  yumemi_lints: ^1.3.0

flutter:
  uses-material-design: true

flutter_launcher_icons:
  android: true
  ios: true
