name: flutter_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.0.1

environment:
  sdk: ^3.6.0
  flutter: ^3.27.1

resolution: workspace

dependencies:
  cores_core:
    path: ../../packages/cores/core
  cores_data:
    path: ../../packages/cores/data
  cores_designsystem:
    path: ../../packages/cores/designsystem
  cores_model:
    path: ../../packages/cores/model
  cores_ui:
    path: ../../packages/cores/ui
  features_debug_mode:
    path: ../../packages/features/debug_mode
  features_force_update:
    path: ../../packages/features/force_update
  features_maintain:
    path: ../../packages/features/maintain
  features_setting:
    path: ../../packages/features/setting
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  freezed_annotation: ^2.4.4
  go_router: ^14.6.3
  intl: ^0.19.0
  json_annotation: ^4.9.0
  package_info_plus: ^8.1.2
  riverpod_annotation: ^2.6.1
  shared_preferences: ^2.3.5

dev_dependencies:
  build_runner: ^2.4.14
  build_verify: ^3.1.0
  custom_lint: ^0.7.0
  flutter_launcher_icons: ^0.14.2
  flutter_test:
    sdk: flutter
  freezed: ^2.5.7
  go_router_builder: ^2.7.2
  json_serializable: ^6.9.0
  riverpod_generator: ^2.6.3
  riverpod_lint: ^2.6.3

flutter:
  uses-material-design: true

flutter_launcher_icons:
  android: true
  ios: true
