name: check-pr

on:
  pull_request:

jobs:
  pre-check:
    permissions:
      pull-requests: write
    outputs:
      src: ${{ steps.filter.outputs.src }}
    runs-on: ubuntu-22.04
    steps:
      - uses: dorny/paths-filter@de90cc6fb38fc0963ad72b210f1f284cd68cea36 # v3.0.2
        id: filter
        with:
          filters: |
            src:
              - "**.dart"
              - "**.yaml"
              - "**/pubspec.lock"
              - "scripts/**"
      - name: Comment
        if: ${{ steps.filter.outputs.src == 'false' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh pr comment -b "チェック対象ファイルの変更がなかったため、checkジョブをスキップしました"

  check:
    needs: pre-check
    if: ${{ needs.pre-check.outputs.src == 'true' }}
    runs-on: ubuntu-22.04
    timeout-minutes: 10

    steps:
      # https://github.com/actions/checkout
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - name: Setup Application Runtime
        uses: ./.github/actions/setup-application-runtime

      # https://github.com/invertase/github-action-dart-analyzer
      - name: Report analyze
        uses: invertase/github-action-dart-analyzer@e981b01a458d0bab71ee5da182e5b26687b7101b # v3.0.0
        with:
          fatal-infos: true

      - name: Report custom_lint result
        run: |
          echo "::add-matcher::.github/problem_matchers/custom_lint.json"
          melos run report_custom_lint:ci --no-select || result=$?
          echo "::remove-matcher owner=custom_lint::"

          if [ -n "$result" ]; then
            exit 1
          fi

      - name: Check format
        run: melos run check_format:ci

      - name: Run test
        run: melos run report_test --no-select
        continue-on-error: true

      # https://github.com/dorny/test-reporter
      - name: Report test
        uses: dorny/test-reporter@eaa763f6ffc21c7a37837f56cd5f9737f27fc6c8 # v1.8.0
        with:
          name: "flutter test"
          path: "(apps|packages/cores|packages/features)/*/test_report.log"
          reporter: "flutter-json"
          fail-on-error: "true"
