name: check-pr

on:
  pull_request:

jobs:
  check:
    runs-on: ubuntu-22.04

    timeout-minutes: 10

    steps:
      # https://github.com/actions/checkout
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      # https://github.com/kuhnroyal/flutter-fvm-config-action
      - name: Fetch flutter config
        uses: kuhnroyal/flutter-fvm-config-action@34c3905bc939a4ff9d9cb07d5a977493fa73b2aa # v2.0
        id: fvm-config-action

      # https://github.com/subosito/flutter-action
      - name: Setup flutter
        uses: subosito/flutter-action@2783a3f08e1baf891508463f8c6653c258246225 # v2.12.0
        with:
          flutter-version: ${{ steps.fvm-config-action.outputs.FLUTTER_VERSION }}
          channel: ${{ steps.fvm-config-action.outputs.FLUTTER_CHANNEL }}

      - name: Setup melos
        run: |
          ln -s $FLUTTER_ROOT .fvm/flutter_sdk
          dart pub global activate melos
          melos bootstrap

      # https://github.com/invertase/github-action-dart-analyzer
      - name: Report analyze
        uses: invertase/github-action-dart-analyzer@1cda5922c6369263b1c7e2fbe281f69704f4d63e # v2.0.0
        with:
          fatal-infos: true

      - name: Report custom_lint result
        run: |
          echo "::add-matcher::.github/problem_matchers/custom_lint.json"
          melos run report_custom_lint:ci --no-select || result=$?
          echo "::remove-matcher owner=custom_lint::"

          if [ -n "$result" ]; then
            exit 1
          fi

      - name: Check format
        run: melos run check_format:ci

      - name: Run test
        run: melos run report_test --no-select
        continue-on-error: true

      # https://github.com/dorny/test-reporter
      - name: Report test
        uses: dorny/test-reporter@eaa763f6ffc21c7a37837f56cd5f9737f27fc6c8 # v1.8.0
        with:
          name: 'flutter test'
          path: '(apps|packages/cores|packages/features)/*/test_report.log'
          reporter: 'flutter-json'
          fail-on-error: 'true'
