name: internal_domain_logic
description: ドメイン層のビジネスロジックを実装するパッケージです。
publish_to: "none"
version: 1.0.0

environment:
  sdk: ^3.8.0

resolution: workspace

dependencies:
  flutter:
    sdk: flutter
  internal_domain_model:
    path: ../domain_model

dev_dependencies:
  test: ^1.25.8
